# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Imports and modules
reorder_imports = true
reorder_modules = true

# Code organization
remove_nested_parens = true
edition = "2021"
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true

# Additional formatting (requires nightly)
wrap_comments = true
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
